#pragma once

#include QMK_KEYBOARD_H

// Matrix size
#define MATRIX_ROWS 3
#define MATRIX_COLS 3

// Pin assignments
#define MATRIX_COL_PINS { RP2040_GPIO10, RP2040_GPIO9, RP2040_GPIO8 }
#define MATRIX_ROW_PINS { RP2040_GPIO7, RP2040_GPIO6, RP2040_GPIO5 }
#define DIODE_DIRECTION COL2ROW

// RGB LEDs
#define RGB_DI_PIN RP2040_GPIO3
#define RGBLED_NUM 1
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_LIMIT_VAL 255
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING

// OLED
#define OLED_DISPLAY_128X32
#define OLED_I2C_SDA_PIN RP2040_GPIO4
#define OLED_I2C_SCL_PIN RP2040_GPIO5
#define OLED_TIMEOUT 0 // never turn off

// Rotary Encoder
#define ENCODERS_PAD_A { RP2040_GPIO1 }
#define ENCODERS_PAD_B { RP2040_GPIO2 }
#define ENCODER_RESOLUTIONS { 4 }